In [ ]:
import pandas as pd

df = pd.read_csv('earthquakes.csv')
#df.mag

## Creating columns

In [ ]:
df.mag

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

In [ ]:
df.sample(10)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
4970,NaN,NaN,00658709,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.011000,NaN,78.32,",nn00658709,",-0.20,ml,...,",nn,",reviewed,1538191749488,"M -0.2 - 61km N of Pahrump, Nevada",0,earthquake,",focal-mechanism,geoserve,origin,phase-data,",-480.0,1539033565853,https://earthquake.usgs.gov/earthquakes/eventp...
7024,NaN,NaN,73089026,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.012860,NaN,51.00,",nc73089026,",1.49,md,...,",nc,",reviewed,1537788363550,"M 1.5 - 6km ESE of Interlaken, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537839184709,https://earthquake.usgs.gov/earthquakes/eventp...
7969,NaN,NaN,20260393,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20260393,",1.50,ml,...,",ak,",automatic,1537575081643,"M 1.5 - 93km W of Willow, Alaska",0,earthquake,",geoserve,origin,",-540.0,1537575469910,https://earthquake.usgs.gov/earthquakes/eventp...
850,NaN,NaN,38319176,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.024680,NaN,31.00,",ci38319176,",1.60,ml,...,",ci,",reviewed,1539202487290,"M 1.6 - 5km WSW of Borrego Springs, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1539203851880,https://earthquake.usgs.gov/earthquakes/eventp...
726,NaN,NaN,20276746,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20276746,",1.80,ml,...,",ak,",automatic,1539234698089,"M 1.8 - 107km NW of Talkeetna, Alaska",0,earthquake,",geoserve,origin,",-540.0,1539234943100,https://earthquake.usgs.gov/earthquakes/eventp...
2488,NaN,NaN,20276228,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20276228,",1.60,ml,...,",ak,",reviewed,1538726104306,"M 1.6 - 36km WSW of Nikiski, Alaska",0,earthquake,",geoserve,origin,phase-data,",-540.0,1539219527964,https://earthquake.usgs.gov/earthquakes/eventp...
2609,NaN,NaN,73093701,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021750,NaN,155.00,",nc73093701,",0.39,md,...,",nc,",reviewed,1538687858060,"M 0.4 - 9km ESE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1538692923797,https://earthquake.usgs.gov/earthquakes/eventp...
3402,NaN,NaN,20269457,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20269457,",1.60,ml,...,",ak,",reviewed,1538503484417,"M 1.6 - 90km WNW of Cantwell, Alaska",0,earthquake,",geoserve,origin,phase-data,",-540.0,1539390096068,https://earthquake.usgs.gov/earthquakes/eventp...
8003,NaN,NaN,20260349,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20260349,",1.80,ml,...,",ak,",automatic,1537566924567,"M 1.8 - 56km SSW of Kaktovik, Alaska",0,earthquake,",geoserve,origin,",-540.0,1537567122388,https://earthquake.usgs.gov/earthquakes/eventp...
2501,NaN,NaN,73093881,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008701,NaN,110.00,",nc73093881,",0.51,md,...,",nc,",reviewed,1538722723030,"M 0.5 - 10km E of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1538777943500,https://earthquake.usgs.gov/earthquakes/eventp...

In [ ]:
df['mag'] # more accurate for dataset in other languages with ' or " symbols

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

In [ ]:
# seperating 2 columns
df[['mag', 'title']]

       mag                                     title
0     1.35             M 1.4 - 9km NE of Aguanga, CA
1     1.29             M 1.3 - 9km NE of Aguanga, CA
2     3.42             M 3.4 - 8km NE of Aguanga, CA
3     0.44             M 0.4 - 9km NE of Aguanga, CA
4     2.16             M 2.2 - 10km NW of Avenal, CA
...    ...                                       ...
9327  0.62      M 0.6 - 9km ENE of Mammoth Lakes, CA
9328  1.00               M 1.0 - 3km W of Julian, CA
9329  2.40  M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330  1.10             M 1.1 - 9km NE of Aguanga, CA
9331  0.66             M 0.7 - 9km NE of Aguanga, CA

[9332 rows x 2 columns]

# Separeting data by list comprehension and strings

In [ ]:
df[
    ['title', 'time']
    + [col for col in df.columns if col.startswith('mag')]
]

                                         title           time   mag magType
0                M 1.4 - 9km NE of Aguanga, CA  1539475168010  1.35      ml
1                M 1.3 - 9km NE of Aguanga, CA  1539475129610  1.29      ml
2                M 3.4 - 8km NE of Aguanga, CA  1539475062610  3.42      ml
3                M 0.4 - 9km NE of Aguanga, CA  1539474978070  0.44      ml
4                M 2.2 - 10km NW of Avenal, CA  1539474716050  2.16      md
...                                        ...            ...   ...     ...
9327      M 0.6 - 9km ENE of Mammoth Lakes, CA  1537230228060  0.62      md
9328               M 1.0 - 3km W of Julian, CA  1537230135130  1.00      ml
9329  M 2.4 - 35km NNE of Hatillo, Puerto Rico  1537229908180  2.40      md
9330             M 1.1 - 9km NE of Aguanga, CA  1537229545350  1.10      ml
9331             M 0.7 - 9km NE of Aguanga, CA  1537228864470  0.66      ml

[9332 rows x 4 columns]

# Slicing

**Selecting and sepertating rows**

In selecting the rows the first used row indexes, last iundex excluded

In [ ]:
df[100:103] [['place', 'time']]

                            place           time
100      25km NW of Ester, Alaska  1539435449480
101  8km ESE of Mammoth Lakes, CA  1539435391320
102        8km ENE of Aguanga, CA  1539435293090

In [ ]:
df[:] [['place', 'time']]

                                 place           time
0                9km NE of Aguanga, CA  1539475168010
1                9km NE of Aguanga, CA  1539475129610
2                8km NE of Aguanga, CA  1539475062610
3                9km NE of Aguanga, CA  1539474978070
4                10km NW of Avenal, CA  1539474716050
...                                ...            ...
9327      9km ENE of Mammoth Lakes, CA  1537230228060
9328               3km W of Julian, CA  1537230135130
9329  35km NNE of Hatillo, Puerto Rico  1537229908180
9330             9km NE of Aguanga, CA  1537229545350
9331             9km NE of Aguanga, CA  1537228864470

[9332 rows x 2 columns]

In [ ]:
df[100:103][['title', 'time']].equals(
    df[['title', 'time']][100:103]
)

True

In [ ]:
df[100:103][['title', 'time']] == df[['title', 'time']][100:103]

     title  time
100   True  True
101   True  True
102   True  True

In [ ]:
# in this code I wanted to lower all letters in Title. It is recommending to use loc
df[100:103]['title'] = df[100:103]['title'].str.lower()

/tmp/ipython-input-3490827836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[100:103]['title'] = df[100:103]['title'].str.lower()
/tmp/ipython-input-3490827836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[100:103]['title'] = df[100:103]['title'].str.lower()

In [ ]:
df[100:103]['title']

100        M 1.2 - 25km NW of Ester, Alaska
101    M 0.6 - 8km ESE of Mammoth Lakes, CA
102          M 1.3 - 8km ENE of Aguanga, CA
Name: title, dtype: object

In [ ]:
df.loc[100:112, 'title'] = df.loc[110:112, 'title'].str.lower()
df.loc[110:112, 'title']

110               m 1.1 - 35km s of ester, alaska
111    m 1.9 - 93km wnw of arctic village, alaska
112      m 0.9 - 20km wsw of smith valley, nevada
Name: title, dtype: object

In [ ]:
df.loc[10:15, ['title', 'mag']]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13
15       M 2.0 - 156km WNW of Haines Junction, Canada  2.00

# With iloc we will seperate by indexes

In [ ]:
df.iloc[10:15, [19, 8]]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13

In [ ]:
df.columns.sort_values()

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [ ]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [ ]:
df.iloc[10:15, [0, 1, 2, 3]]

   alert  cdi        code                                             detail
10   NaN  NaN    37389162  https://earthquake.usgs.gov/fdsnws/event/1/que...
11   NaN  NaN  2018286010  https://earthquake.usgs.gov/fdsnws/event/1/que...
12   NaN  NaN    37389146  https://earthquake.usgs.gov/fdsnws/event/1/que...
13   NaN  NaN    1000hbti  https://earthquake.usgs.gov/fdsnws/event/1/que...
14   NaN  NaN    73096921  https://earthquake.usgs.gov/fdsnws/event/1/que...

In [ ]:
df.iloc[10:15, 6:10]

      gap             ids   mag magType
10   57.0    ,ci37389162,  0.50      ml
11  186.0  ,pr2018286010,  2.77      md
12   76.0    ,ci37389146,  0.50      ml
13  157.0    ,us1000hbti,  4.50      mb
14   71.0    ,nc73096921,  2.13      md

In [ ]:
df.iloc[10:15, 0:10]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType
10,NaN,NaN,37389162,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.005116,NaN,57.0,",ci37389162,",0.50,ml
11,NaN,NaN,2018286010,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.947700,NaN,186.0,",pr2018286010,",2.77,md
12,NaN,NaN,37389146,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.015170,NaN,76.0,",ci37389146,",0.50,ml
13,NaN,NaN,1000hbti,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.193000,NaN,157.0,",us1000hbti,",4.50,mb
14,NaN,NaN,73096921,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026410,NaN,71.0,",nc73096921,",2.13,md

In [ ]:
df.iloc[10:15, 6:10].equals(
    df.loc[10:14, 'detail':'mmi']
)

False

# Scalar qiymatlarni qidirish

Biz loc va iloc yordamida dataframe dan kichik qisimlarni tanladik. Ammo, agar biz faqat ma'lum bir [qator, ustun] da joylashgan aniq qiymatga qiziqsak, unda iat va at ni ishlatishimiz mumkin.
at etiketlar bilan ishlatiladiu

In [ ]:
df.at[10, 'mag']  # accessing by column title

np.float64(0.5)

In [ ]:
df.iat[10, 8]  # accessing by column index

np.float64(0.5)

# Filtering our data

Filtering by Boolean mask

In [ ]:
df.mag > 2

0       False
1       False
2        True
3       False
4        True
        ...
9327    False
9328    False
9329     True
9330    False
9331    False
Name: mag, Length: 9332, dtype: bool

In [ ]:
df[df.mag > 2]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.02137,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.07799,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
5,NaN,NaN,2018286011,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.43730,NaN,158.0,",pr2018286011,",2.61,md,...,",pr,",reviewed,1539473686440,"M 2.6 - 55km ESE of Punta Cana, Dominican Repu...",0,earthquake,",geoserve,origin,phase-data,",-300.0,1539500579236,https://earthquake.usgs.gov/earthquakes/eventp...
9,NaN,NaN,1000hbtn,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.19100,NaN,37.0,",us1000hbtn,",4.70,mb,...,",us,",reviewed,1539472814760,"M 4.7 - 219km SSE of Saparua, Indonesia",0,earthquake,",geoserve,origin,phase-data,",540.0,1539473712040,https://earthquake.usgs.gov/earthquakes/eventp...
11,NaN,NaN,2018286010,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.94770,NaN,186.0,",pr2018286010,",2.77,md,...,",pr,",reviewed,1539471621260,"M 2.8 - 53km SE of Punta Cana, Dominican Republic",0,earthquake,",geoserve,origin,phase-data,",-300.0,1539500530876,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9317,NaN,NaN,38064023,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.11560,NaN,142.0,",ci38064023,",2.64,ml,...,",ci,",reviewed,1537232796810,"M 2.6 - 4km SW of Delta, B.C., MX",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537281340288,https://earthquake.usgs.gov/earthquakes/eventp...
9319,NaN,NaN,2000hg5w,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.66300,NaN,40.0,",us2000hg5w,",4.40,mb,...,",us,",reviewed,1537231966170,"M 4.4 - 58km W of San Antonio de los Cobres, A...",0,earthquake,",geoserve,origin,phase-data,",-180.0,1538871593040,https://earthquake.usgs.gov/earthquakes/eventp...
9320,NaN,NaN,38064007,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.04743,NaN,113.0,",ci38064007,",2.81,ml,...,",ci,",reviewed,1537231284810,"M 2.8 - 8km NW of Delta, B.C., MX",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537234531589,https://earthquake.usgs.gov/earthquakes/eventp...
9321,NaN,NaN,2000hjsq,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.29600,NaN,61.0,",us2000hjsq,",4.30,mb,...,",us,",reviewed,1537231275500,"M 4.3 - 19km NE of Cateel, Philippines",0,earthquake,",geoserve,origin,phase-data,",480.0,1538890521040,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.45260,NaN,276.0,",pr2018261000,",2.40,md,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...

In [ ]:
  df[df.mag >= 7.0]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...

In [ ]:
  df.mag >= 7.0

0       False
1       False
2       False
3       False
4       False
        ...
9327    False
9328    False
9329    False
9330    False
9331    False
Name: mag, Length: 9332, dtype: bool

In [ ]:
df.loc[
    df.mag >= 7.0,
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'time', 'type']
]

,alert,mag,magType,title,tsunami,time,type
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,1539204500290,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,1538128963480,earthquake

from matplotlib import pyplot as plt
_df_2['mag'].plot(kind='hist', bins=20, title='mag')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['time'].plot(kind='hist', bins=20, title='time')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('alert').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='mag', y='time', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['mag']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'mag'}, axis=1)
              .sort_values('mag', ascending=True))
  xs = counted['mag']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('mag', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('alert')):
  _plot_series(series, series_name, i)
  fig.legend(title='alert', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('mag')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['mag']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'mag'}, axis=1)
              .sort_values('mag', ascending=True))
  xs = counted['mag']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('mag', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('title')):
  _plot_series(series, series_name, i)
  fig.legend(title='title', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('mag')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['tsunami']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'tsunami'}, axis=1)
              .sort_values('tsunami', ascending=True))
  xs = counted['tsunami']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('tsunami', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('alert')):
  _plot_series(series, series_name, i)
  fig.legend(title='alert', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('tsunami')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['tsunami']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'tsunami'}, axis=1)
              .sort_values('tsunami', ascending=True))
  xs = counted['tsunami']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('tsunami', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('title')):
  _plot_series(series, series_name, i)
  fig.legend(title='title', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('tsunami')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_11['mag'].plot(kind='line', figsize=(8, 4), title='mag')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['time'].plot(kind='line', figsize=(8, 4), title='time')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['title'].value_counts()
    for x_label, grp in _df_13.groupby('alert')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('alert')
_ = plt.ylabel('title')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['alert'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='mag', y='alert', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['title'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='mag', y='title', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['alert'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='time', y='alert', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['title'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='time', y='title', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.loc[
    (df.tsunami ==1) & (df.alert == 'green'),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
118,green,6.70,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
501,green,5.60,mww,"M 5.6 - 128km SE of Kimbe, Papua New Guinea",1,earthquake
799,green,6.50,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
816,green,6.20,mww,"M 6.2 - 94km SW of Kokopo, Papua New Guinea",1,earthquake
826,green,5.90,mww,"M 5.9 - 117km ESE of Kimbe, Papua New Guinea",1,earthquake
829,green,5.90,mww,"M 5.9 - 113km ESE of Kimbe, Papua New Guinea",1,earthquake
837,green,7.00,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
838,green,6.10,mb,"M 6.1 - 132km E of Kimbe, Papua New Guinea",1,earthquake
1015,green,5.00,ml,"M 5.0 - 61km SSW of Chignik Lake, Alaska",1,earthquake
1273,green,4.00,ml,"M 4.0 - 71km SW of Kaktovik, Alaska",1,earthquake
1795,green,4.00,ml,"M 4.0 - 60km WNW of Valdez, Alaska",1,earthquake
2414,green,3.83,mw,"M 3.8 - 5km SW of Tres Pinos, CA",1,earthquake
2752,green,4.00,ml,"M 4.0 - 67km SSW of Kaktovik, Alaska",1,earthquake
3609,green,5.60,mww,"M 5.6 - 33km SSW of Nggongi Satu, Indonesia",1,earthquake
3692,green,5.90,mww,"M 5.9 - 30km SSW of Nggongi, Indonesia",1,earthquake
3699,green,6.00,mww,"M 6.0 - 33km S of Nggongi Satu, Indonesia",1,earthquake
4363,green,6.70,mww,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake
4988,green,4.41,mw,"M 4.4 - 1km SE of Delta, B.C., MX",1,earthquake
5196,green,5.70,ms_20,"M 5.7 - 107km N of Palu, Indonesia",1,earthquake
5244,green,5.70,mb,"M 5.7 - 17km NNE of Palu, Indonesia",1,earthquake
5256,green,5.80,mb,"M 5.8 - 21km SSE of Palu, Indonesia",1,earthquake
5258,green,5.70,mb,"M 5.7 - 17km E of Palu, Indonesia",1,earthquake
5259,green,5.80,mb,"M 5.8 - 99km N of Palu, Indonesia",1,earthquake
5323,green,6.10,mww,"M 6.1 - 55km NNW of Palu, Indonesia",1,earthquake
9133,green,5.10,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake

In [ ]:
df.loc[
    (df.place.str.contains('Alaska')) & (df.alert.notnull()),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type', 'place']
]

,alert,mag,magType,title,tsunami,type,place
1015,green,5.0,ml,"M 5.0 - 61km SSW of Chignik Lake, Alaska",1,earthquake,"61km SSW of Chignik Lake, Alaska"
1273,green,4.0,ml,"M 4.0 - 71km SW of Kaktovik, Alaska",1,earthquake,"71km SW of Kaktovik, Alaska"
1795,green,4.0,ml,"M 4.0 - 60km WNW of Valdez, Alaska",1,earthquake,"60km WNW of Valdez, Alaska"
2752,green,4.0,ml,"M 4.0 - 67km SSW of Kaktovik, Alaska",1,earthquake,"67km SSW of Kaktovik, Alaska"
3260,green,3.9,ml,"M 3.9 - 44km N of North Nenana, Alaska",0,earthquake,"44km N of North Nenana, Alaska"
4101,green,4.2,ml,"M 4.2 - 131km NNW of Arctic Village, Alaska",0,earthquake,"131km NNW of Arctic Village, Alaska"
6897,green,3.8,ml,"M 3.8 - 80km SSW of Kaktovik, Alaska",0,earthquake,"80km SSW of Kaktovik, Alaska"
8524,green,3.8,ml,"M 3.8 - 69km SSW of Kaktovik, Alaska",0,earthquake,"69km SSW of Kaktovik, Alaska"
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake,"64km SSW of Kaktovik, Alaska"

In [ ]:
df.loc[
    (df.place.str.contains(r'CA$|California$')) & (df.mag > 0),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type', 'place']
]

,alert,mag,magType,title,tsunami,type,place
0,NaN,1.35,ml,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,"9km NE of Aguanga, CA"
1,NaN,1.29,ml,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,"9km NE of Aguanga, CA"
2,NaN,3.42,ml,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,"8km NE of Aguanga, CA"
3,NaN,0.44,ml,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,"9km NE of Aguanga, CA"
4,NaN,2.16,md,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,"10km NW of Avenal, CA"
...,...,...,...,...,...,...,...
9326,NaN,1.82,ml,"M 1.8 - 4km W of Julian, CA",0,earthquake,"4km W of Julian, CA"
9327,NaN,0.62,md,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,"9km ENE of Mammoth Lakes, CA"
9328,NaN,1.00,ml,"M 1.0 - 3km W of Julian, CA",0,earthquake,"3km W of Julian, CA"
9330,NaN,1.10,ml,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,"9km NE of Aguanga, CA"
9331,NaN,0.66,ml,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,"9km NE of Aguanga, CA"

In [ ]:
df.loc[
    df.mag.between(6.5, 7.5),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
4363,green,6.7,mww,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [ ]:
[df.mag.idxmin(), df.mag.idxmax()]

[2409, 5263]

In [ ]:
df.loc[
    [df.mag.idxmin(), df.mag.idxmax()],
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
2409,NaN,-1.26,ml,"M -1.3 - 41km ENE of Adak, Alaska",0,earthquake
5263,red,7.50,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [ ]:
df.filter(items=['mag', 'magType']).head()

    mag magType
0  1.35      ml
1  1.29      ml
2  3.42      ml
3  0.44      ml
4  2.16      md

In [ ]:
df.filter(like='mag').head()

    mag magType
0  1.35      ml
1  1.29      ml
2  3.42      ml
3  0.44      ml
4  2.16      md

In [ ]:
df.filter(regex=r'^t').head()

,time,title,tsunami,type,types,tz
0,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0
1,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0
2,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0
3,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0
4,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0